### ISSUE TITLE
Settings hangs when trying to open developer options

### ISSUE THREAD

**Issue by boswelja** [AOSP-CAF/platform_packages_apps_Settings#4]

**Comment by Meninblack007** [comment]
Any logs?

**Comment by boswelja** [comment]
I'm just doing another build, I'll try get logs once this one is installed (Also no audio, and microphone doesn't work on my Moto G3)

**Comment by boswelja** [comment]
[2017-04-22-11-29-02.txt](https://github.com/AOSP-CAF/platform_packages_apps_Settings/files/948559/2017-04-22-11-29-02.txt)
@Meninblack007 I have made some modifications to Settings, but most of them are just trying to fix Development Settings (Nothing has made a difference)

**Comment by boswelja** [comment]
UPDATE: The only changes I have made to settings is removing the buttons preferences (Development settings was broken before that change).
I was able to fix audio by either:
1. Remove the ffmpeg include from my devices audio config
2. Or include LineageOS stagefright-plugins and apply some patches to frameworks/av and system/media (Also fixed camera hanging when taking a picture and microphone)

**Comment by Meninblack007** [comment]
Remove ffmepg from media_codecs.xml

**Comment by boswelja** [comment]
@Meninblack007 in my fork, I added lineageos stagefright-plugins as video playback from the browser doesn't seem to work without it

**Comment by ethanbanker** [comment]
frp might cause develoopment hang

**Comment by boswelja** [comment]
@ethanbanker2428 frp?

**Comment by ethanbanker** [comment]
Message me on telegram so I can explain it. @boswelja idk how your device works so

**Comment by ethanbanker** [comment]
@EthanBanker is the habdle

**Comment by boswelja** [comment]
@ethanbanker2428 give me a minute to install telegram and make an account

**Comment by akhilnarang** [comment]
@boswelja you're using MultiROM?

**Comment by boswelja** [comment]
@akhilnarang nope, although I probably should so I don't have to restore backups all the time cx
